#!/bin/sh

INPUT=$1
#PG=2/m_uab
PG=6
NAME=`basename "$INPUT" .stream`
SLURMFILE="$NAME.sh"
echo "#!/bin/sh" > $SLURMFILE
echo >> $SLURMFILE
#echo "#source /reg/g/cfel/crystfel/crystfel-dev/bin/indexamajig" > $SLURMFILE
echo >> $SLURMFILE
echo "#SBATCH -p htc" >> $SLURMFILE
echo "#SBATCH -J $NAME" >> $SLURMFILE
echo "#SBATCH -o $NAME.out" >> $SLURMFILE
echo "#SBATCH -e $NAME.err" >> $SLURMFILE
echo "#SBATCH -t 0-04:00:00" >> $SLURMFILE                                  
echo "#SBATCH -N 1" >> $SLURMFILE                                           
echo "#SBATCH -n 20 " >> $SLURMFILE                                     
    # It may be polite to set the priority very low to allow other jobs through:
    #echo "#SBATCH --nice=100" >> $SLURMFILE                                    
echo >> $SLURMFILE                                                          
                                                                                
echo "#SBATCH --job-name=$NAME" >> $SLURMFILE                               
echo "#SBATCH --mail-type=END" >> $SLURMFILE                                
echo "#SBATCH --mail-user=Gihan.Ketawala@asu.edu" >> $SLURMFILE             
echo >> $SLURMFILE    
command="$command partialator -i $INPUT -o $NAME.hkl -y $PG -j 20"
command="$command --iterations=3 --model=unity --max-adu=80000 --polarisation=vert "
echo $command >> $SLURMFILE

# Set your queue after "-q" below
sbatch $SLURMFILE
