#!/bin/sh

INPUT=$1
#PG=2/m_uab
PG=622
NAME=`basename "$INPUT" .stream`
SLURMFILE="$NAME.sh"
echo "#!/bin/sh" > $SLURMFILE
echo >> $SLURMFILE
#echo "#source /reg/g/cfel/crystfel/crystfel-dev/bin/indexamajig" > $SLURMFILE
echo >> $SLURMFILE
command="$command partialator -i $INPUT -o $NAME.hkl -y $PG -j 16"
command="$command --max-adu=8000 --iterations=3 --model=unity --polarisation=vert"
echo $command >> $SLURMFILE

# Set your queue after "-q" below
bsub -q psfehprioq -o $NAME.out -e $NAME.err -J $NAME -x sh $SLURMFILE
